### ISSUE TITLE
Remove Flutter dependency

### ISSUE THREAD

**Issue by larryaasen** [DigitalKatalis/test_cov_console#13]
This is a very nice package and very valuable. I see this package depends on Flutter, but I don't see any code that depends on Flutter. To make this package easier to use with Dart only packages, can the dependency for Flutter be removed?

**Comment by dk-imudita** [comment]
Yes, the flutter dependency has been removed on 0.1.2.

**Comment by dk-imudita** [comment]
It is dev_dependencies for unit testing.
