### ISSUE TITLE
Excluding files from lcov

### ISSUE THREAD

**Issue by ShivamMattoo33** [DigitalKatalis/test_cov_console#19]
Hello,

Thanks for this awesome package.
Just to give some context of what i am trying to achieve is that I want to check test coverage only for new test files that have been added in Pull request
The way we write our files is if Code file is a.dart then test file a_test.dart
So i can run flutter test -- coverage 'new test files'

Now I want to exclude all files except files that correspond to test files from the lcov(e.g if new test file in PR was a_test.dart lcov should only have a.dart)  so I can basically make sure the new test files added have 90% or more coverage with respect to its relative UI/code file . Is there a way to achieve it with this plugin?

**Comment by dk-imudita** [comment]
The current plugin only read the output of `flutter test --coverage`, It does not change or interfere the flow or logic on `flutter test --coverage`. So I am afraid it is not possible to achieve it on current plugin.
However as far as I know there is a feature on Sonarqube that has similar functionality that could show the coverage for the new code only. And it seems it calculate the value for the source control (i.e. git). Frankly I don't know how to do it yet.

I will put this as future feature.

Let me know if you have some sample code or documentation about it.

Thanks,

Made

**Comment by dk-imudita** [comment]
Hello,

The last version has some options to produce coverage with include/exclude files:

-e, --exclude=<STRING1,STRING2,...>  A list of contains string for files without unit testing to be excluded from report.
-n, --include=<STRING1,STRING2,...>  A list of contains string for files to be include from report.

Hope it would solve your issue.

Thanks ..

**Comment by dk-imudita** [comment]
Closed.
