### ISSUE TITLE
Excluding files or directories from coverage report

### ISSUE THREAD

**Issue by tjcampanella** [DigitalKatalis/test_cov_console#20]
Hello I am trying to only show the coverage report for files other than my views. To do that I need to pass in strings for directories or files but it does not seem to work. 

Command: flutter pub run test_cov_console --exclude=freezed, _bloc_state, _bloc_event, .config, presentation/pages, presentation/widgets, models/classes, models/forum, models/settings

This command does not filter out all files matching that path and it does not change the total percent coverage. Please advise as I would really like to use your package. Thank you!

**Comment by dk-imudita** [comment]
Hi,

You are reporting two issues here:
1. The command does not filter out all files matching that path. Please make sure there is no spaces between the file names
` 
freezed, _bloc_state, _bloc_event, .config, presentation/pages, 
` 
It should be:
` 
freezed,_bloc_state,_bloc_event,.config,presentation/pages
`
3. The total percentage is not changes. For this one please use the version 0.2.1. I just fixed it.

Thanks,

Made
