### ISSUE TITLE
how to check specific folder to test

### ISSUE THREAD

**Issue by indratrisnar** [DigitalKatalis/test_cov_console#25]
i have project which use modular.
so to cek test coverage, i have to check each of mudular cd(sub directory/module).

how to test all module test, from root terminal/project?

**Comment by dk-imudita** [comment]
Please refer to README.md for `report for multiple lcov.info files (-m, --multi)`

**Comment by indratrisnar** [comment]
But how to combine all lcov.info in another module. Like:
lib (root)
test (root)
SearchModule/test/search.test
MovieModule/test/find.test


Pada Kam, 7 Des 2023 19.04, I Made Mudita ***@***.***>
menulis:

**Comment by dk-imudita** [comment]
Just follow as per README, here I copy paste for you:
It support to run for multiple lcov.info files with the followings directory structures:
1. No root module
<root>/<module_a>
<root>/<module_a>/coverage/lcov.info
<root>/<module_a>/lib/src
<root>/<module_b>
<root>/<module_b>/coverage/lcov.info
<root>/<module_b>/lib/src
...
2. With root module
<root>/coverage/lcov.info
<root>/lib/src
<root>/<module_a>
<root>/<module_a>/coverage/lcov.info
<root>/<module_a>/lib/src
<root>/<module_b>
<root>/<module_b>/coverage/lcov.info
<root>/<module_b>/lib/src
...
You must run test_cov_console on <root> dir, and the report would be grouped by module, here is
the sample output for directory structure 'with root module':
flutter pub run test_cov_console --file=coverage/lcov.info --exclude=_constants,_mock --multi

**Comment by indratrisnar** [comment]
Thanks, it work in separate module result.

Then how to merge the result?

For example, i have 1 project, iniside this project i have 2 module:
- core module
- search module

Each module has test.

I want to check test coverage where the result of percentage is merge (core
& search) in 1 table.

If i use:
`dart run test_cov_console --file=coverage/lcov.info
--exclude=_constants,_mock --multi`
It return 2 table result (core table, search table), so the percentage test
it depend each module/table. Not depend all module ( 1 project)


Pada Jum, 8 Des 2023 08.02, I Made Mudita ***@***.***>
menulis:

**Comment by dk-imudita** [comment]
this tool only read  lcov.info and report with readable format. It does not recalculate or merge the result if it is from multiple lcov.info file.
So if you want to have single report from multiple lcov.info files, you should merge your lcov.info files first, before run this tools.

**Comment by indratrisnar** [comment]
Ok thank you

Pada Jum, 8 Des 2023 08.27, I Made Mudita ***@***.***>
menulis:
