### ISSUE TITLE
Running against a merged lcov.info file creates repeats in the report.

### ISSUE THREAD

**Issue by spekary** [DigitalKatalis/test_cov_console#6]
I am running multiple tests and using the --merge-coverage option of flutter test to merge the coverage reports of multiple different tests, including integration tests. 

When running test_cov_console against the report, I get repeated files with different results. I was expecting the results to be merged. For example, this report is generated:

lib/                                         |         |         |         |                   |
 appBar.dart                                 |  100.00 |  100.00 |   93.10 |           44,96,97|
 badgeWidget.dart                            |  100.00 |  100.00 |    0.00 |...5,26,28,29,30,31|
 bottomBar.dart                              |  100.00 |  100.00 |   91.30 |...,155,156,159,172|
 connect.dart                                |  100.00 |  100.00 |   21.92 |...,536,539,540,543|
 dashboard.dart                              |  100.00 |  100.00 |   30.85 |...6,1017,1018,1020|
 dayScreens.dart                             |  100.00 |  100.00 |    0.00 |...,300,301,302,303|
 dialog.dart                                 |  100.00 |  100.00 |    1.20 |...,239,240,241,242|
 dialogComplications.dart                    |  100.00 |  100.00 |    0.00 |...,118,121,122,124|
 dialogGrade.dart                            |  100.00 |  100.00 |    0.00 |...,137,138,139,142|
 util.dart                                   |    0.00 |    0.00 |    0.00 |    no unit testing|
 legal.dart                                  |    0.00 |    0.00 |    0.00 |    no unit testing|
lib/gen2/                                    |         |         |         |                   |
 app_starter.dart                            |  100.00 |  100.00 |   62.22 |...0,61,63,68,74,78|
lib/                                         |         |         |         |                   |
 info.dart                                   |  100.00 |  100.00 |   52.10 |...,504,505,508,509|
 legal.dart                                  |  100.00 |  100.00 |   70.00 |...4,89,90,91,92,93|

...

Notice that lib/legal.dart is repeated. I presume its because the --merge-coverage option simply appends the data. It is up to the lcov.info reader to actually merge the results.

**Comment by spekary** [comment]
Getting better. There are no repeating files, but still getting repeating directories:

lib/                                         |         |         |         |                   |
 appBar.dart                                 |  100.00 |  100.00 |   93.10 |           44,96,97|
 badgeWidget.dart                            |  100.00 |  100.00 |    0.00 |...5,26,28,29,30,31|
 bottomBar.dart                              |  100.00 |  100.00 |   91.30 |...,155,156,159,172|
 config.dart                                 |    0.00 |    0.00 |    0.00 |    no unit testing|
 connect.dart                                |  100.00 |  100.00 |   21.92 |...,536,539,540,543|
 dashboard.dart                              |  100.00 |  100.00 |   30.85 |...6,1017,1018,1020|
 dayScreens.dart                             |  100.00 |  100.00 |    0.00 |...,300,301,302,303|
 dialog.dart                                 |  100.00 |  100.00 |    1.20 |...,239,240,241,242|
 dialogComplications.dart                    |  100.00 |  100.00 |    0.00 |...,118,121,122,124|
 dialogGrade.dart                            |  100.00 |  100.00 |    0.00 |...,137,138,139,142|
 live_rd.dart                                |    0.00 |    0.00 |    0.00 |    no unit testing|
 routes.dart                                 |    0.00 |    0.00 |    0.00 |    no unit testing|
lib/gen2/                                    |         |         |         |                   |
 app_starter.dart                            |  100.00 |  100.00 |   62.22 |...0,61,63,68,74,78|
lib/                                         |         |         |         |                   |
 info.dart                                   |  100.00 |  100.00 |   52.10 |...,504,505,508,509|
 legal.dart                                  |  100.00 |  100.00 |   70.00 |...4,89,90,91,92,93|
lib/gen2/                                    |         |         |         |                   |
 main_mock.dart                              |    0.00 |    0.00 |    0.00 |    no unit testing|
 main_prod.dart                              |    0.00 |    0.00 |    0.00 |    no unit testing|
 main_rd.dart                                |    0.00 |    0.00 |    0.00 |    no unit testing|
 main_stage.dart                             |    0.00 |    0.00 |    0.00 |    no unit testing|
lib/legal/                                   |         |         |         |                   |
 dataprot.dart                               |  100.00 |  100.00 |    0.00 |...7,89,90,93,94,96|
 legalInfo.dart                              |  100.00 |  100.00 |   73.08 |...,167,168,171,172|
 license.dart                                |  100.00 |  100.00 |    0.00 |...0,92,93,96,97,99|
 oss.dart                                    |  100.00 |  100.00 |    0.00 |...,154,156,157,159|
 ossLicenses.dart                            |  100.00 |  100.00 |    0.00 |                  6|
 publisher.dart                              |  100.00 |  100.00 |    0.00 |...0,91,92,95,96,98|
lib/                                         |         |         |         |                   |
 live.dart                                   |  100.00 |  100.00 |    0.00 |...,584,585,586,587|
 login.dart                                  |  100.00 |  100.00 |    0.00 |...9,66,68,73,75,80|
lib/model/                                   |         |         |         |                   |
 appPrefs.dart                               |  100.00 |  100.00 |   21.57 |...,111,112,113,114|
 model.dart                                  |  100.00 |  100.00 |   12.37 |...,487,488,489,492|
 procedure.dart                              |  100.00 |  100.00 |    0.00 |...,436,439,440,443|
 procedure.g.dart                            |  100.00 |  100.00 |    0.00 |...,140,143,144,145|
 recording.dart                              |  100.00 |  100.00 |    0.00 |...9,90,91,92,93,94|
 types.dart                                  |  100.00 |  100.00 |    0.00 |...6,17,18,19,20,26|
lib/                                         |         |         |         |                   |
 monthScreen.dart                            |  100.00 |  100.00 |    0.00 |...,245,247,249,253|
 onBoardingScreen.dart                       |  100.00 |  100.00 |   78.95 |...,196,197,198,215|
 plainButtonBar.dart                         |  100.00 |  100.00 |   74.58 |...,107,109,110,112|
 postop.dart                                 |  100.00 |  100.00 |    0.14 |...4,1315,1316,1317|
 procedureGraph.dart                         |  100.00 |  100.00 |    0.00 |...,521,522,523,525|
 procedureListTile.dart                      |  100.00 |  100.00 |    0.00 |...0,92,93,94,96,97|
 profile.dart                                |  100.00 |  100.00 |   77.78 |...,113,114,115,116|
lib/remote/                                  |         |         |         |                   |
 api.dart                                    |  100.00 |  100.00 |    0.00 |...4,66,114,115,116|
 cloud.dart                                  |  100.00 |  100.00 |    0.98 |...,282,284,285,286|
 zeissID.dart                                |  100.00 |  100.00 |    0.00 |...,112,113,116,119|
lib/                                         |         |         |         |                   |
 theme.dart                                  |  100.00 |  100.00 |   46.15 |...,224,226,230,231|
 toast.dart                                  |  100.00 |  100.00 |    0.00 |...92,95,97,101,102|
 util.dart                                   |  100.00 |  100.00 |   10.00 |...9,50,54,58,59,60|
lib/util/                                    |         |         |         |                   |
 env.dart                                    |  100.00 |  100.00 |   50.00 |        44,50,55,58|
lib/                                         |         |         |         |                   |
 weekScreens.dart

**Comment by dk-imudita** [comment]
I could not replicate this issue on my environment this time. could you send me lcov.info file for further investigation.

**Comment by dk-imudita** [comment]
Hi Shannon,

I just published version 0.1.0 that support multiple lcov.info files. It will print the report for multiple lcov.info files, so you don't need to run flutter test with '--merge-coverage' at all. I think it will solve most of the issues that I mentioned previously.

Regards,

Made
